### ISSUE TITLE
Error: Caused by: java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by gwolosh** [bg7/BG7#33]
gene = D7X5Y8 completed!
Realizando la peticion post...
Exception in thread "main" java.lang.InternalError
        at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:755)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:169)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:194)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at sun.misc.Launcher$ExtClassLoader.findClass(Launcher.java:229)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at java.util.ResourceBundle$RBClassLoader.loadClass(ResourceBundle.java:435)
        at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2289)
        at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1364)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1328)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1282)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1224)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:705)
        at java.util.logging.Level.getLocalizedName(Level.java:223)
        at java.util.logging.SimpleFormatter.format(SimpleFormatter.java:64)
        at java.util.logging.StreamHandler.publish(StreamHandler.java:177)
        at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:88)
        at java.util.logging.Logger.log(Logger.java:478)
        at java.util.logging.Logger.doLog(Logger.java:500)
        at java.util.logging.Logger.logp(Logger.java:616)
        at org.apache.commons.logging.impl.Jdk14Logger.log(Jdk14Logger.java:99)
        at org.apache.commons.logging.impl.Jdk14Logger.info(Jdk14Logger.java:194)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:439)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at com.era7.lib.bioinfo.bioinfoutil.uniprot.UniprotProteinRetreiver.getUniprotDataFor(UniprotProteinRetreiver.java:41)
        at com.era7.bioinfo.annotation.FillDataFromUniprot.main(FillDataFromUniprot.java:88)
        at com.era7.bioinfo.annotation.FillDataFromUniprot.execute(FillDataFromUniprot.java:44)
        at com.era7.lib.bioinfo.bioinfoutil.ExecuteFromFile.main(ExecuteFromFile.java:66)
        at com.era7.bioinfo.annotation.BG7.main(BG7.java:32)
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:127)
        at java.util.jar.JarFile.<init>(JarFile.java:135)
        at java.util.jar.JarFile.<init>(JarFile.java:72)
        at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:646)
        at sun.misc.URLClassPath$JarLoader.access$600(URLClassPath.java:540)
        at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:607)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:599)
        at sun.misc.URLClassPath$JarLoader.getR

**Comment by pablopareja** [comment]
Hi @gwolosh 

I'm not sure why you are getting this exception but it's likely that it may have something to do with the connection with the Uniprot WS and closing the connection from their side for some reason.

Could you provide me with the XML file you are using as input for the program FillDataFromUniprot ?

If that's not an option because of privacy issues, could you run the program again and see if you get the same exception at the very same execution point? _(I mean right after you get as output 'gene = D7X5Y8 completed!' in this case)_

**Comment by gwolosh** [comment]
This was run using the bg7_example_input_files.

Glenn (Gedaliah) Wolosh

**Comment by pablopareja** [comment]
OK, but I'd need to have a look at your BLAST output XML file to gather more information about the possible cause _(AFAIK that one is not included in the bg7_example_input_files)_

**Comment by gwolosh** [comment]
Is this the file you want -- bg7project_proteins_tBLASTn.xml

If so I don't see how to upload it.

Glenn (Gedaliah) Wolosh

**Comment by pablopareja** [comment]
Yeah I meant that file.
You can send it to me by e-mail (ppareja "at" era7 "dot" com) or give me a public URL from where I could download it.

Pablo

**Comment by gwolosh** [comment]
Let me know when you get the file

http://sirius2.umdnj.edu/~woloshgm/downloads/bg7project_proteins_tBLASTn.xml.gz

## 

Glenn (Gedaliah) Wolosh
gwolosh@gmail.com

**Comment by pablopareja** [comment]
Hey,
I already downloaded your file, I was having a look at it but I didn't see anything strange so far. 
Could you send me as well all the files that were created by the program till you got this exception? 

Thanks.

**Comment by gwolosh** [comment]
http://sirius2.umdnj.edu/~woloshgm/downloads/testout.tgz
and
http://sirius2.umdnj.edu/~woloshgm/downloads/test_bg7.o33115.gz

Glenn (Gedaliah) Wolosh

**Comment by pablopareja** [comment]
Hi Glenn,

Thanks for the files. 
I've been having a look at all this and apparently there's no reason to get this exception.
The only possibility I can think about is that the Uniprot WS could be closing the connection or something like that making the program crash, (I just checked out that the program had already gathered the information from more than 1000 proteins, and this looks to me like a value big enough as for them to somehow prevent you getting more information at least for a while)

I tried to add a quick fix for this kind of situations adding a try-catch block that encloses the part where this is carried out; however for some reason I don't understand this exception is not properly managed and the program keeps crashing.

So, I can think of two different workarounds for this:
1. Use Bio4j instead and you'll get rid of all this limitations/trouble with Uniprot WS _(actually one of the reasons for us to start Bio4j project was this...)_
2. You can try to launch that part of the pipeline again and see if they don't close the connection this time. _For this you can comment out your executions.xml file up to the program com.era7.bioinfo.annotation.FillDataFromUniprot so that you don't have to spend time running the same things again._

Hope this helps,

Pablo

**Comment by gwolosh** [comment]
OK, thanks

Glenn (Gedaliah) Wolosh

**Comment by gwolosh** [comment]
Hi,

I ran it again and it crashed in the same place.

Glenn (Gedaliah) Wolosh

**Comment by pablopareja** [comment]
Hi Glenn,

I ran the program 'FillDataFromUniprot' with the exact same data and jar file that you passed me and I didn't get any exception, the program completed successfully. 
So I don't know what else can I do right now to help you figure out what's going on when you execute it in your machine... :confused:

Pablo

**Comment by eparejatobes** [comment]
closing this, reopen if there's any further info available
