### ISSUE TITLE
GenerateFastaFiles fails

### ISSUE THREAD

**Issue by intikhab** [bg7/BG7#37]
Dear BG7,

Your BG7 setup looks quite interesting and I was testing it on one of our genomes. Manually going through different steps I notice that only GenerateFastaFiles code fails all others run correctly.

I get the following error:

Could not find the main class: com.era7.bioinfo.annotation.GenerateFastaFiles. Program will exit.

If it would have been a classpath problem, other tools in BG7 may also complain but it is only GenerateFastaFiles.

Any Help Please?

Intikhab

PS. Following is a test for different tools in BG7. I have downloaded the master branch from github last week.

```

alamis:BG7-master$ java -jar jars/PredictGenes.jar 
This program expects six parameters: 
1. BlastOutput XML filename 
2. Contigs FNA filename 
3. Output results XML filename 
4. Maximum gene length (integer)
5. Flag (boolean) indicating if this genome corresponds to a virus (true/false)
6. Dif span (integer)

alamis:BG7-master$ java -jar jars/GenerateFastaFiles.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: com/era7/lib/bioinfo/bioinfoutil/Executable
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Caused by: java.lang.ClassNotFoundException: com.era7.lib.bioinfo.bioinfoutil.Executable
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 12 more
Could not find the main class: com.era7.bioinfo.annotation.GenerateFastaFiles. Program will exit.
alamis:BG7-master$ java -jar jars/GenerateGffFile.jar 
This program expects two parameters: 
1. Input predicted genes XML filename 
2. Output GFF filename



```

**Comment by pablopareja** [comment]
Hi Intikhab,

Thanks for opening this issue, I just realized that the /jar folder of the master branch had a lot of deprecated old jars that shouldn't be used anymore _(things were updated in the develop branch but I forgot to do so in the master one)_

The right way to execute any program from BG7's pipeline is by means of the jar called 
**BG7.jar** together with an executions XML file where you can specify the sequence of programs that should be run, _(in any case I got rid of the old jar files so that this cannot happen again to someone else)_.
You can find a template of the executions.xml file here: https://github.com/bg7/BG7/blob/master/executionsTemplate.xml

Hope this helps.
