### ISSUE TITLE
run BG7 locally

### ISSUE THREAD

**Issue by haruosuz** [bg7/BG7#39]
Dear BG7 Team:

I was wondering if there is any documentation about how to run BG7 locally. I could not find any example syntax/scripts to run the program from the command-line at http://bg7.ohnosequences.com and https://github.com/bg7/bg7/wiki. I would appreciate any feedback you can give.

Thank you,
paruo

**Comment by rtobes** [comment]
There is not significant differences between run BG7 locally or in the cloud.

You can find some information about how to run BG7 here:
http://bg7.ohnosequences.com/faq/#hardware-reqs

**Comment by haruosuz** [comment]
Thank you for your reply.
I downloaded the 'BG7-master' directory by clicking [Download ZIP] at https://github.com/bg7/BG7.
Could you provide me with the expected output file names when running bg7 in bg7_example_input_files?

I typed the following commands.
cd BG7-master/bg7_example_input_files
../bin/bg7 --genome escherichia_coli_o104_h4_str._ty-2482_1_supercontigs.fasta \
--proteins EHEC_ReferenceProteins_17_08_2012.fasta \
--rnas EHEC_Reference_RNAs.frn \
--genetic_code genetic_code.txt \
--genbank_data GenBankExternalData.xml

This generated the following output files,
bg7project.genome.db.log
bg7project.genome.db.nhr
bg7project.genome.db.nin
bg7project.genome.db.nsq
bg7project_proteins_tBLASTn.xml
bg7project_ReferenceProteins.fasta
bg7project_RNA_blastn.xml
bg7project.rnas.db.log
bg7project.rnas.db.nhr
bg7project.rnas.db.nin
bg7project.rnas.db.nsq
bg7project_sequences.fna
params.log

and printed the following message.
cp: _snip_/BG7-master/bg7_example_input_files/genetic_code.txt' and _snip_/BG7-master/bg7_example_input_files/genetic_code.txt' are the same file

Running bg7 with --project_name and --out options printed the following message.
cp: cannot stat `/jar/bg7.jar': No such file or directory

**Comment by krittima2525** [comment]
Dear paruo,

```
I tried to run them like your command but it was not showed any output files. Could you suggest me about this error? My command is 
```

~/Documents/BG7/bin/bg7 --genome escherichia_coli_o104_h4_str._ty-2482_1_supercontigs.fasta \

> > --proteins EHEC_ReferenceProteins_17_08_2012.fasta \
> > --rnas EHEC_Reference_RNAs.frn \
> > --genetic_code genetic_code.txt \
> > --genbank_data GenBankExternalData.xml
> > Error message : -bash: /Users/linamac/Documents/BG7/bin/bg7: Permission denied

So I changed command to run by BG7.jar as following command;
java -jar BG7.jar bg7 --genome escherichia_coli_o104_h4_str._ty-2482_1_supercontigs.fasta --proteins EHEC_ReferenceProteins_17_08_2012.fasta --rnas EHEC_Reference_RNAs.frn --genetics_code genetic_code.txt --genbank_data GenBankExternalData.xml

The output was showed as following;
Aug 20, 2014 9:28:14 PM com.era7.lib.bioinfo.bioinfoutil.ExecuteFromFile main
SEVERE: null
java.io.FileNotFoundException: executions.xml (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:131)
    at java.io.FileReader.<init>(FileReader.java:72)
    at com.era7.lib.bioinfo.bioinfoutil.ExecuteFromFile.main(ExecuteFromFile.java:37)
    at com.era7.bioinfo.annotation.BG7.main(BG7.java:32)

So I don't know why it was occurred. Thank you in advance for your suggestion.

Krittima

**Comment by haruosuz** [comment]
Alternatively, you can use Prokka for prokaryotic genome annotation.
http://www.vicbioinformatics.com/software.prokka.shtml
http://www.ncbi.nlm.nih.gov/pubmed/24642063

**Comment by krittima2525** [comment]
Dear Paruo,

```
Thank you for your kindness.
```

Best regards,
Krittima

2014-08-20 23:24 GMT+07:00 paruo notifications@github.com:

> Alternatively, you can use Prokka for prokaryotic genome annotation.
> http://www.vicbioinformatics.com/software.prokka.shtml
> http://www.ncbi.nlm.nih.gov/pubmed/24642063
> 
> On Aug 20, 2014, at 8:33, krittima2525 notifications@github.com wrote:
> 
> > Dear paruo,
> > 
> > I tried to run them like your command but it was not showed any output
> > files. Could you suggest me about this error? My command is
> > ~/Documents/BG7/bin/bg7 --genome
> > escherichia_coli_o104_h4_str._ty-2482_1_supercontigs.fasta \
> > 
> > --proteins EHEC_ReferenceProteins_17_08_2012.fasta \
> > --rnas EHEC_Reference_RNAs.frn \
> > --genetic_code genetic_code.txt \
> > --genbank_data GenBankExternalData.xml
> > Error message : -bash: /Users/linamac/Documents/BG7/bin/bg7: Permission
> > denied
> > 
> > So I changed command to run by BG7.jar as following command;
> > java -jar BG7.jar bg7 --genome
> > escherichia_coli_o104_h4_str._ty-2482_1_supercontigs.fasta --proteins
> > EHEC_ReferenceProteins_17_08_2012.fasta --rnas EHEC_Reference_RNAs.frn
> > --genetics_code genetic_code.txt --genbank_data GenBankExternalData.xml
> > 
> > The output was showed as following;
> > Aug 20, 2014 9:28:14 PM com.era7.lib.bioinfo.bioinfoutil.ExecuteFromFile
> > main
> > SEVERE: null
> > java.io.FileNotFoundException: executions.xml (No such file or
> > directory)
> > at java.io.FileInputStream.open(Native Method)
> > at java.io.FileInputStream.(FileInputStream.java:131)
> > at java.io.FileReader.(FileReader.java:72)
> > at
> > com.era7.lib.bioinfo.bioinfoutil.ExecuteFromFile.main(ExecuteFromFile.java:37)
> > 
> > at com.era7.bioinfo.annotation.BG7.main(BG7.java:32)
> > 
> > So I don't know why it was occurred. Thank you in advance for your
> > suggestion.
> > 
> > Krittima
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bg7/BG7/issues/39#issuecomment-52803060.

## 

Krittima Anekthanakul
Aquatic animal Researcher and Biostatician
Veterinary Medical Aquatic animal Research Center (VMARC)
Faculty of Veterinary Science,
Chulalongkorn University,
Henri-Dunant Rd., Pathumwan,
Bangkok 10330, Thailand
Tel (66) 2251 8887
Fax (66) 2251 8887
Mobile (668) 4078 8300
